/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.nuix.avro;

import com.univocity.parsers.annotations.Parsed;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class AusNews extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = 5768832713976123162L;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AusNews\",\"namespace\":\"com.nuix.avro\",\"fields\":[{\"name\":\"rating\",\"type\":[\"null\",\"float\"],\"default\":null},{\"name\":\"news_agency\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"link\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"title\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"page_views\",\"type\":[\"null\",\"int\"],\"default\":null}]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static SpecificData MODEL$ = new SpecificData();

    private static final BinaryMessageEncoder<AusNews> ENCODER =
            new BinaryMessageEncoder<AusNews>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<AusNews> DECODER =
            new BinaryMessageDecoder<AusNews>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<AusNews> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<AusNews> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<AusNews> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<AusNews>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this AusNews to a ByteBuffer.
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a AusNews from a ByteBuffer.
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a AusNews instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static AusNews fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    @Parsed(index = 0)
    private java.lang.Float rating;
    @Parsed(index = 1)
    private java.lang.CharSequence news_agency;
    @Parsed(index = 2)
    private java.lang.CharSequence link;
    @Parsed(index = 3)
    private java.lang.CharSequence title;
    @Parsed(index = 4)
    private java.lang.Integer page_views;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public AusNews() {
    }

    /**
     * All-args constructor.
     * @param rating The new value for rating
     * @param news_agency The new value for news_agency
     * @param link The new value for link
     * @param title The new value for title
     * @param page_views The new value for page_views
     */
    public AusNews(java.lang.Float rating, java.lang.CharSequence news_agency, java.lang.CharSequence link, java.lang.CharSequence title, java.lang.Integer page_views) {
        this.rating = rating;
        this.news_agency = news_agency;
        this.link = link;
        this.title = title;
        this.page_views = page_views;
    }

    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return rating;
            case 1:
                return news_agency;
            case 2:
                return link;
            case 3:
                return title;
            case 4:
                return page_views;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                rating = (java.lang.Float) value$;
                break;
            case 1:
                news_agency = (java.lang.CharSequence) value$;
                break;
            case 2:
                link = (java.lang.CharSequence) value$;
                break;
            case 3:
                title = (java.lang.CharSequence) value$;
                break;
            case 4:
                page_views = (java.lang.Integer) value$;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'rating' field.
     * @return The value of the 'rating' field.
     */
    public java.lang.Float getRating() {
        return rating;
    }


    /**
     * Sets the value of the 'rating' field.
     * @param value the value to set.
     */
    public void setRating(java.lang.Float value) {
        this.rating = value;
    }

    /**
     * Gets the value of the 'news_agency' field.
     * @return The value of the 'news_agency' field.
     */
    public java.lang.CharSequence getNewsAgency() {
        return news_agency;
    }


    /**
     * Sets the value of the 'news_agency' field.
     * @param value the value to set.
     */
    public void setNewsAgency(java.lang.CharSequence value) {
        this.news_agency = value;
    }

    /**
     * Gets the value of the 'link' field.
     * @return The value of the 'link' field.
     */
    public java.lang.CharSequence getLink() {
        return link;
    }


    /**
     * Sets the value of the 'link' field.
     * @param value the value to set.
     */
    public void setLink(java.lang.CharSequence value) {
        this.link = value;
    }

    /**
     * Gets the value of the 'title' field.
     * @return The value of the 'title' field.
     */
    public java.lang.CharSequence getTitle() {
        return title;
    }


    /**
     * Sets the value of the 'title' field.
     * @param value the value to set.
     */
    public void setTitle(java.lang.CharSequence value) {
        this.title = value;
    }

    /**
     * Gets the value of the 'page_views' field.
     * @return The value of the 'page_views' field.
     */
    public java.lang.Integer getPageViews() {
        return page_views;
    }


    /**
     * Sets the value of the 'page_views' field.
     * @param value the value to set.
     */
    public void setPageViews(java.lang.Integer value) {
        this.page_views = value;
    }

    /**
     * Creates a new AusNews RecordBuilder.
     * @return A new AusNews RecordBuilder
     */
    public static com.nuix.avro.AusNews.Builder newBuilder() {
        return new com.nuix.avro.AusNews.Builder();
    }

    /**
     * Creates a new AusNews RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new AusNews RecordBuilder
     */
    public static com.nuix.avro.AusNews.Builder newBuilder(com.nuix.avro.AusNews.Builder other) {
        if (other == null) {
            return new com.nuix.avro.AusNews.Builder();
        } else {
            return new com.nuix.avro.AusNews.Builder(other);
        }
    }

    /**
     * Creates a new AusNews RecordBuilder by copying an existing AusNews instance.
     * @param other The existing instance to copy.
     * @return A new AusNews RecordBuilder
     */
    public static com.nuix.avro.AusNews.Builder newBuilder(com.nuix.avro.AusNews other) {
        if (other == null) {
            return new com.nuix.avro.AusNews.Builder();
        } else {
            return new com.nuix.avro.AusNews.Builder(other);
        }
    }

    /**
     * RecordBuilder for AusNews instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AusNews>
            implements org.apache.avro.data.RecordBuilder<AusNews> {

        private java.lang.Float rating;
        private java.lang.CharSequence news_agency;
        private java.lang.CharSequence link;
        private java.lang.CharSequence title;
        private java.lang.Integer page_views;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(com.nuix.avro.AusNews.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.rating)) {
                this.rating = data().deepCopy(fields()[0].schema(), other.rating);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.news_agency)) {
                this.news_agency = data().deepCopy(fields()[1].schema(), other.news_agency);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
            if (isValidValue(fields()[2], other.link)) {
                this.link = data().deepCopy(fields()[2].schema(), other.link);
                fieldSetFlags()[2] = other.fieldSetFlags()[2];
            }
            if (isValidValue(fields()[3], other.title)) {
                this.title = data().deepCopy(fields()[3].schema(), other.title);
                fieldSetFlags()[3] = other.fieldSetFlags()[3];
            }
            if (isValidValue(fields()[4], other.page_views)) {
                this.page_views = data().deepCopy(fields()[4].schema(), other.page_views);
                fieldSetFlags()[4] = other.fieldSetFlags()[4];
            }
        }

        /**
         * Creates a Builder by copying an existing AusNews instance
         * @param other The existing instance to copy.
         */
        private Builder(com.nuix.avro.AusNews other) {
            super(SCHEMA$);
            if (isValidValue(fields()[0], other.rating)) {
                this.rating = data().deepCopy(fields()[0].schema(), other.rating);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.news_agency)) {
                this.news_agency = data().deepCopy(fields()[1].schema(), other.news_agency);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.link)) {
                this.link = data().deepCopy(fields()[2].schema(), other.link);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.title)) {
                this.title = data().deepCopy(fields()[3].schema(), other.title);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.page_views)) {
                this.page_views = data().deepCopy(fields()[4].schema(), other.page_views);
                fieldSetFlags()[4] = true;
            }
        }

        /**
         * Gets the value of the 'rating' field.
         * @return The value.
         */
        public java.lang.Float getRating() {
            return rating;
        }


        /**
         * Sets the value of the 'rating' field.
         * @param value The value of 'rating'.
         * @return This builder.
         */
        public com.nuix.avro.AusNews.Builder setRating(java.lang.Float value) {
            validate(fields()[0], value);
            this.rating = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'rating' field has been set.
         * @return True if the 'rating' field has been set, false otherwise.
         */
        public boolean hasRating() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'rating' field.
         * @return This builder.
         */
        public com.nuix.avro.AusNews.Builder clearRating() {
            rating = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'news_agency' field.
         * @return The value.
         */
        public java.lang.CharSequence getNewsAgency() {
            return news_agency;
        }


        /**
         * Sets the value of the 'news_agency' field.
         * @param value The value of 'news_agency'.
         * @return This builder.
         */
        public com.nuix.avro.AusNews.Builder setNewsAgency(java.lang.CharSequence value) {
            validate(fields()[1], value);
            this.news_agency = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'news_agency' field has been set.
         * @return True if the 'news_agency' field has been set, false otherwise.
         */
        public boolean hasNewsAgency() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'news_agency' field.
         * @return This builder.
         */
        public com.nuix.avro.AusNews.Builder clearNewsAgency() {
            news_agency = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        /**
         * Gets the value of the 'link' field.
         * @return The value.
         */
        public java.lang.CharSequence getLink() {
            return link;
        }


        /**
         * Sets the value of the 'link' field.
         * @param value The value of 'link'.
         * @return This builder.
         */
        public com.nuix.avro.AusNews.Builder setLink(java.lang.CharSequence value) {
            validate(fields()[2], value);
            this.link = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        /**
         * Checks whether the 'link' field has been set.
         * @return True if the 'link' field has been set, false otherwise.
         */
        public boolean hasLink() {
            return fieldSetFlags()[2];
        }


        /**
         * Clears the value of the 'link' field.
         * @return This builder.
         */
        public com.nuix.avro.AusNews.Builder clearLink() {
            link = null;
            fieldSetFlags()[2] = false;
            return this;
        }

        /**
         * Gets the value of the 'title' field.
         * @return The value.
         */
        public java.lang.CharSequence getTitle() {
            return title;
        }


        /**
         * Sets the value of the 'title' field.
         * @param value The value of 'title'.
         * @return This builder.
         */
        public com.nuix.avro.AusNews.Builder setTitle(java.lang.CharSequence value) {
            validate(fields()[3], value);
            this.title = value;
            fieldSetFlags()[3] = true;
            return this;
        }

        /**
         * Checks whether the 'title' field has been set.
         * @return True if the 'title' field has been set, false otherwise.
         */
        public boolean hasTitle() {
            return fieldSetFlags()[3];
        }


        /**
         * Clears the value of the 'title' field.
         * @return This builder.
         */
        public com.nuix.avro.AusNews.Builder clearTitle() {
            title = null;
            fieldSetFlags()[3] = false;
            return this;
        }

        /**
         * Gets the value of the 'page_views' field.
         * @return The value.
         */
        public java.lang.Integer getPageViews() {
            return page_views;
        }


        /**
         * Sets the value of the 'page_views' field.
         * @param value The value of 'page_views'.
         * @return This builder.
         */
        public com.nuix.avro.AusNews.Builder setPageViews(java.lang.Integer value) {
            validate(fields()[4], value);
            this.page_views = value;
            fieldSetFlags()[4] = true;
            return this;
        }

        /**
         * Checks whether the 'page_views' field has been set.
         * @return True if the 'page_views' field has been set, false otherwise.
         */
        public boolean hasPageViews() {
            return fieldSetFlags()[4];
        }


        /**
         * Clears the value of the 'page_views' field.
         * @return This builder.
         */
        public com.nuix.avro.AusNews.Builder clearPageViews() {
            page_views = null;
            fieldSetFlags()[4] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public AusNews build() {
            try {
                AusNews record = new AusNews();
                record.rating = fieldSetFlags()[0] ? this.rating : (java.lang.Float) defaultValue(fields()[0]);
                record.news_agency = fieldSetFlags()[1] ? this.news_agency : (java.lang.CharSequence) defaultValue(fields()[1]);
                record.link = fieldSetFlags()[2] ? this.link : (java.lang.CharSequence) defaultValue(fields()[2]);
                record.title = fieldSetFlags()[3] ? this.title : (java.lang.CharSequence) defaultValue(fields()[3]);
                record.page_views = fieldSetFlags()[4] ? this.page_views : (java.lang.Integer) defaultValue(fields()[4]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<AusNews>
            WRITER$ = (org.apache.avro.io.DatumWriter<AusNews>) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<AusNews>
            READER$ = (org.apache.avro.io.DatumReader<AusNews>) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override
    protected boolean hasCustomCoders() {
        return true;
    }

    @Override
    public void customEncode(org.apache.avro.io.Encoder out)
            throws java.io.IOException {
        if (this.rating == null) {
            out.writeIndex(0);
            out.writeNull();
        } else {
            out.writeIndex(1);
            out.writeFloat(this.rating);
        }

        if (this.news_agency == null) {
            out.writeIndex(0);
            out.writeNull();
        } else {
            out.writeIndex(1);
            out.writeString(this.news_agency);
        }

        if (this.link == null) {
            out.writeIndex(0);
            out.writeNull();
        } else {
            out.writeIndex(1);
            out.writeString(this.link);
        }

        if (this.title == null) {
            out.writeIndex(0);
            out.writeNull();
        } else {
            out.writeIndex(1);
            out.writeString(this.title);
        }

        if (this.page_views == null) {
            out.writeIndex(0);
            out.writeNull();
        } else {
            out.writeIndex(1);
            out.writeInt(this.page_views);
        }

    }

    @Override
    public void customDecode(org.apache.avro.io.ResolvingDecoder in)
            throws java.io.IOException {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            if (in.readIndex() != 1) {
                in.readNull();
                this.rating = null;
            } else {
                this.rating = in.readFloat();
            }

            if (in.readIndex() != 1) {
                in.readNull();
                this.news_agency = null;
            } else {
                this.news_agency = in.readString(this.news_agency instanceof Utf8 ? (Utf8) this.news_agency : null);
            }

            if (in.readIndex() != 1) {
                in.readNull();
                this.link = null;
            } else {
                this.link = in.readString(this.link instanceof Utf8 ? (Utf8) this.link : null);
            }

            if (in.readIndex() != 1) {
                in.readNull();
                this.title = null;
            } else {
                this.title = in.readString(this.title instanceof Utf8 ? (Utf8) this.title : null);
            }

            if (in.readIndex() != 1) {
                in.readNull();
                this.page_views = null;
            } else {
                this.page_views = in.readInt();
            }

        } else {
            for (int i = 0; i < 5; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        if (in.readIndex() != 1) {
                            in.readNull();
                            this.rating = null;
                        } else {
                            this.rating = in.readFloat();
                        }
                        break;

                    case 1:
                        if (in.readIndex() != 1) {
                            in.readNull();
                            this.news_agency = null;
                        } else {
                            this.news_agency = in.readString(this.news_agency instanceof Utf8 ? (Utf8) this.news_agency : null);
                        }
                        break;

                    case 2:
                        if (in.readIndex() != 1) {
                            in.readNull();
                            this.link = null;
                        } else {
                            this.link = in.readString(this.link instanceof Utf8 ? (Utf8) this.link : null);
                        }
                        break;

                    case 3:
                        if (in.readIndex() != 1) {
                            in.readNull();
                            this.title = null;
                        } else {
                            this.title = in.readString(this.title instanceof Utf8 ? (Utf8) this.title : null);
                        }
                        break;

                    case 4:
                        if (in.readIndex() != 1) {
                            in.readNull();
                            this.page_views = null;
                        } else {
                            this.page_views = in.readInt();
                        }
                        break;

                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }
}










